<?php 
$helper = \Magento\Framework\App\ObjectManager::getInstance()->get('Mageplaza\SteavisGarantis\Helper\Data'); 
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeName = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Store\Model\StoreManagerInterface::class)->getStore()->getName();
$required_loc = $this->helper('Mageplaza\SteavisGarantis\Helper\Data')->getConfig('sagwidget/jswidget/enablereview');
$fr_api = $helper->FrenchApi();
$en_api = $helper->EnglishApi();
$de_api = $helper->GermanApi();
$es_api = $helper->SpanishApi();
$it_api = $helper->ItalianApi();
$nl_api = $helper->NetherlandApi();

$api_fr = substr($fr_api, 0, 4);
$api_en = substr($en_api, 0, 4);
$api_de = substr($de_api, 0, 4);
$api_es = substr($es_api, 0, 4);
$api_it = substr($it_api, 0, 4);
$api_nl = substr($nl_api, 0, 4);
//echo 'FR'.$api_fr .'EN'. $api_en; 
if($helper->isEnable()) : 
	if($storeName =='English'){ ?>
		<script type="text/javascript">var agSiteId="<?php echo $api_en; ?>";</script>
		<script src="https://www.guaranteed-reviews.com/wp-content/plugins/ag-core/widgets/JsWidget.js" type="text/javascript"></script>
	<?php }
	else if($storeName =='France'){ ?>
		<script type="text/javascript">var agSiteId="<?php echo $api_fr; ?>";</script>
		<script src="https://www.societe-des-avis-garantis.fr/wp-content/plugins/ag-core/widgets/JsWidget.js" type="text/javascript"></script>
	<?php	}
	else if($storeName =='German'){ ?>
		<script type="text/javascript">var agSiteId="<?php echo $api_de; ?>";</script>
		<script src="https://www.g-g-b.de/wp-content/plugins/ag-core/widgets/JsWidget.js" type="text/javascript"></script>
	<?php	}
	else if($storeName =='Spanish'){ ?>
		<script type="text/javascript">var agSiteId="<?php echo $api_es; ?>";</script>
		<script src="https://www.sociedad-de-opiniones-contrastadas.es/wp-content/plugins/ag-core/widgets/JsWidget.js" type="text/javascript"></script>
	<?php	}
	else if($storeName =='Italian'){ ?>
		<script type="text/javascript">var agSiteId="<?php echo $api_it; ?>";</script>
		<script src="https://www.societa-recensioni-garantite.it/wp-content/plugins/ag-core/widgets/JsWidget.js" type="text/javascript"></script>
	<?php	}
	else if($storeName =='Netherland'){ ?>
		<script type="text/javascript">var agSiteId="<?php echo $api_nl; ?>";</script>
		<script src="https://www.g-b-n.nl/wp-content/plugins/ag-core/widgets/JsWidget.js" type="text/javascript"></script>
	<?php	}
endif; ?>