<?php 
$helper = \Magento\Framework\App\ObjectManager::getInstance()->get('Mageplaza\SteavisGarantis\Helper\Data'); 
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeName = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Store\Model\StoreManagerInterface::class)->getStore()->getName();
$storeCode = $storeManager->getStore()->getCode();
$required_loc = $this->helper('Mageplaza\SteavisGarantis\Helper\Data')->getConfig('sagwidget/jswidget/enablereview');
$fr_api = $helper->FrenchApi();
$en_api = $helper->EnglishApi();
$de_api = $helper->GermanApi();
$es_api = $helper->SpanishApi();
$it_api = $helper->ItalianApi();
$nl_api = $helper->NetherlandApi();

$api_fr = substr($fr_api, 0, 4);
$api_en = substr($en_api, 0, 4);
$api_de = substr($de_api, 0, 4);
$api_es = substr($es_api, 0, 4);
$api_it = substr($it_api, 0, 4);
$api_nl = substr($nl_api, 0, 4);

//echo 'FR'.$api_fr .'EN'. $api_en; 
//echo $storeManager->getStore()->getStoreId();
//echo $storeName;
//echo "Store Code:"; 
//echo $storeCode; echo "<br/>";
if($helper->isEnableiframe()) : 
	//Footer Iframe
	if($storeCode =='en' && $required_loc ==0){ ?>
		<iframe width="100%" height="221" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.guaranteed-reviews.com/wp-content/plugins/ag-core/widgets/iframe/2/h/?id=<?php echo $api_en; ?>"> </iframe>
<?php }
	else if($storeCode =='fr' && $required_loc ==0){ ?>
		<iframe width="100%" height="221" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.societe-des-avis-garantis.fr/wp-content/plugins/ag-core/widgets/iframe/2/h/?id=<?php echo $api_fr; ?>"> </iframe>
<?php	}
	else if($storeCode =='de' && $required_loc ==0){ ?>
		<iframe width="100%" height="221" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.g-g-b.de/wp-content/plugins/ag-core/widgets/iframe/2/h/?id=<?php echo $api_de; ?>"> </iframe>
<?php	}
	else if($storeCode =='es' && $required_loc ==0){ ?>
		<iframe width="100%" height="221" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.sociedad-de-opiniones-contrastadas.es/wp-content/plugins/ag-core/widgets/iframe/2/h/?id=<?php echo $api_es; ?>"> </iframe>
<?php	}
	else if($storeCode =='it' && $required_loc ==0){ ?>
		<iframe width="100%" height="221" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.societa-recensioni-garantite.it/wp-content/plugins/ag-core/widgets/iframe/2/h/?id=<?php echo $api_it; ?>"> </iframe>
<?php	}
	else if($storeCode =='nl' && $required_loc ==0){ ?>
		<iframe width="100%" height="221" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.g-b-n.nl/wp-content/plugins/ag-core/widgets/iframe/2/h/?id=<?php echo $api_nl; ?>"> </iframe>
<?php	}
		
	//Right Iframe
	else if($storeCode =='en' && $required_loc ==1){ ?>
		<div class="right_irfame">
			<iframe width="100%" height="221" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.guaranteed-reviews.com/wp-content/plugins/ag-core/widgets/iframe/2/v/?id=<?php echo $api_en; ?>"> </iframe>
		</div>
<?php }
	else if($storeCode =='fr' && $required_loc ==1){ ?>
		<div class="right_irfame">
			<iframe width="100%" height="221" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.societe-des-avis-garantis.fr/wp-content/plugins/ag-core/widgets/iframe/2/v/?id=<?php echo $api_fr; ?>"> </iframe>
		</div>
<?php	}
	else if($storeCode =='de' && $required_loc ==1){ ?>
		<div class="right_irfame">
			<iframe width="100%" height="221" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.g-g-b.de/wp-content/plugins/ag-core/widgets/iframe/2/v/?id=<?php echo $api_de; ?>"> </iframe>
		</div>
<?php	}
	else if($storeCode =='es' && $required_loc ==1){ ?>
		<div class="right_irfame">
			<iframe width="100%" height="221" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.sociedad-de-opiniones-contrastadas.es/wp-content/plugins/ag-core/widgets/iframe/2/v/?id=<?php echo $api_es; ?>"> </iframe>
		</div>
<?php	}
	else if($storeCode =='it' && $required_loc ==1){ ?>
		<div class="right_irfame">
			<iframe width="100%" height="221" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.societa-recensioni-garantite.it/wp-content/plugins/ag-core/widgets/iframe/2/v/?id=<?php echo $api_it; ?>"> </iframe>
		</div>
<?php	}
	else if($storeCode =='nl' && $required_loc ==1){ ?><div class="right_irfame">
			<iframe width="100%" height="221" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.g-b-n.nl/wp-content/plugins/ag-core/widgets/iframe/2/v/?id=<?php echo $api_nl; ?>"> </iframe>
		</div>
<?php	}
	
	//Left Iframe
	else if($storeCode =='en' && $required_loc ==2){ ?>
		<div class="left_iframe">
			<iframe width="100%" height="221" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.guaranteed-reviews.com/wp-content/plugins/ag-core/widgets/iframe/2/v/?id=<?php echo $api_en; ?>"> </iframe>
		</div>
<?php }
	else if($storeCode =='fr' && $required_loc ==2){ ?>
		<div class="left_iframe">
			<iframe width="100%" height="221" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.societe-des-avis-garantis.fr/wp-content/plugins/ag-core/widgets/iframe/2/v/?id=<?php echo $api_fr; ?>"> </iframe>
		</div>
<?php	}
	else if($storeCode =='de' && $required_loc ==2){ ?>
		<div class="left_iframe">
			<iframe width="100%" height="221" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.g-g-b.de/wp-content/plugins/ag-core/widgets/iframe/2/v/?id=<?php echo $api_de; ?>"> </iframe>
		</div>
<?php	}
	else if($storeCode =='es' && $required_loc ==2){ ?>
		<div class="left_iframe">
			<iframe width="100%" height="221" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.sociedad-de-opiniones-contrastadas.es/wp-content/plugins/ag-core/widgets/iframe/2/v/?id=<?php echo $api_es; ?>"> </iframe>
		</div>
<?php	}
	else if($storeCode =='it' && $required_loc ==2){ ?>
		<div class="left_iframe">
			<iframe width="100%" height="221" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.societa-recensioni-garantite.it/wp-content/plugins/ag-core/widgets/iframe/2/v/?id=<?php echo $api_it; ?>"> </iframe>
		</div>
<?php	}
	else if($storeCode =='nl' && $required_loc ==2){ ?><div class="left_iframe">
			<iframe width="100%" height="221" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.g-b-n.nl/wp-content/plugins/ag-core/widgets/iframe/2/v/?id=<?php echo $api_nl; ?>"> </iframe>
		</div>
<?php	}
	endif;
//echo $required_loc;
/* if($required_loc ==0){
	echo 'Footer';
}
else if($required_loc ==1){
	echo 'Right';
}
else if($required_loc ==2){
	echo 'Left';
} */
?>
