<?php
/**
 * @var $block \Vendor\Module\Block\Module
 */
?>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<div class="custom-content">
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('Avis clients')->toHtml(); 
		$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
		$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
		$storeName = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Store\Model\StoreManagerInterface::class)->getStore()->getName();
		$storeCode = $storeManager->getStore()->getCode();
		$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
		$connection = $resource->getConnection();
		$tableName = $resource->getTableName('sag_review');
		//get current product
		$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
		$product_id = $product->getId();
		$lang = $storeManager->getStore()->getCode(); 
		//Select Data from table
		//$sql = "Select * FROM ". $tableName. " WHERE idProduct =". $product_id;
		$sql = $connection->select()
            ->from($tableName)
            ->where('idProduct = ?',$product_id)
            ->where('lang = ?',$lang);
		$result = $connection->fetchAll($sql);
		
		/*Review Average*/
		//$result_count = "Select review_rating FROM ". $tableName. " WHERE idProduct =". $product_id;
		$result_count = $connection->select('review_rating')
            ->from($tableName)
            ->where('idProduct = ?',$product_id)
            ->where('lang = ?',$lang);
		$data=$connection->fetchAll($result_count);
		$count = count($data);
		$sum = array_sum(array_column($data,'review_rating'));
		$average = $sum/$count;
		//echo "Store Code:"; 
		//echo $storeCode; echo "<br/>";
		$helper = \Magento\Framework\App\ObjectManager::getInstance()->get('Mageplaza\SteavisGarantis\Helper\Data'); 
		//public $basedon;
		if($storeCode =='fr'){ 
			$basedon = 'Basé sur';
			$review = 'avis';
			$view_review = 'VOIR LES AVIS';
		}
		else if($storeCode =='en'){ 
			$basedon = 'Based on' ;
			$review = 'Reviews';
			$view_review = 'SEE REVIEWS';
		}
		else if($storeCode =='de'){ 
			$basedon = 'Beyogen auf';
			$review = 'Meinung';
			$view_review = 'BEWERTUNGEN ANSEHEN';
		}
		else if($storeCode =='es'){ 
			$basedon = 'Basado en';
			$review = 'Reseñas';
			$view_review = 'VER RESEÑAS';
		}
		else if($storeCode =='it'){ 
			$basedon = 'Basato su';
			$review = 'Recensioni';
			$view_review = 'VEDI RECENSIONI';
		}
		else if($storeCode =='nl'){ 
			$basedon = 'Gebaseerd op';
			$review = 'Beoordelingen';
			$view_review = 'BEKIJK BEOORDELINGEN';
		}
		
		if($helper->isEnablestarrating()) : ?>
		<div class="top_widget">

		<div class="widget_img">
		<?php if($storeCode =='fr'){ ?>
			<img src="<?php echo $this->getViewFileUrl('Mageplaza_SteavisGarantis::images/sag_logo_badge.png'); ?>" />
		<?php }
			else if($storeCode =='en'){ ?>
			<img src="<?php echo $this->getViewFileUrl('Mageplaza_SteavisGarantis::images/sag_logo_badge_en.png'); ?>" />
		<?php }
			else if($storeCode =='de'){ ?>
			<img src="<?php echo $this->getViewFileUrl('Mageplaza_SteavisGarantis::images/sag_logo_badge_de.png'); ?>" />
		<?php }
			else if($storeCode =='es'){ ?>
			<img src="<?php echo $this->getViewFileUrl('Mageplaza_SteavisGarantis::images/sag_logo_badge_es.png'); ?>" />
		<?php }
			else if($storeCode =='it'){ ?>
			<img src="<?php echo $this->getViewFileUrl('Mageplaza_SteavisGarantis::images/sag_logo_badge_it.png'); ?>" />
		<?php }
			else if($storeCode =='nl'){ ?>
			<img src="<?php echo $this->getViewFileUrl('Mageplaza_SteavisGarantis::images/sag_logo_badge_nl.png'); ?>" />
			
		<?php }?>
		
		
		</div>



    <!-- Your category condition here -->
    <?php 
		
		//echo $count.'<br>';
		//echo $average.'<br>';
		//echo $sum;
		
		echo '<div class="ave_rate"><div class="bh-stars" data-bh-rating=' .$average.'>
							<svg version="1.1" class="bh-star bh-star--1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24" xml:space="preserve"><path class="outline" d="M12,4.2L14.5,9l0.2,0.5l0.5,0.1l5.5,0.8L16.8,14l-0.4,0.4l0.1,0.5l1,5.3l-5-2.5L12,17.5l-0.4,0.2l-5,2.5L7.5,15l0.1-0.5 L7.2,14l-4-3.7l5.5-0.8l0.5-0.1L9.5,9L12,4.2 M11.9,2L8.6,8.6L1,9.7l5.5,5.1L5.2,22l6.8-3.4l6.8,3.4l-1.3-7.2L23,9.6l-7.6-1L11.9,2 L11.9,2z"/><polygon class="full" points="18.8,22 12,18.6 5.2,22 6.5,14.8 1,9.7 8.6,8.6 11.9,2 15.4,8.6 23,9.6 17.5,14.7"/><polyline class="left-half" points="12,18.6 5.2,22 6.5,14.8 1,9.7 8.6,8.6 11.9,2"/></svg>
							
							<svg version="1.1" class="bh-star bh-star--2" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24" xml:space="preserve"><path class="outline" d="M12,4.2L14.5,9l0.2,0.5l0.5,0.1l5.5,0.8L16.8,14l-0.4,0.4l0.1,0.5l1,5.3l-5-2.5L12,17.5l-0.4,0.2l-5,2.5L7.5,15l0.1-0.5 L7.2,14l-4-3.7l5.5-0.8l0.5-0.1L9.5,9L12,4.2 M11.9,2L8.6,8.6L1,9.7l5.5,5.1L5.2,22l6.8-3.4l6.8,3.4l-1.3-7.2L23,9.6l-7.6-1L11.9,2 L11.9,2z"/><polygon class="full" points="18.8,22 12,18.6 5.2,22 6.5,14.8 1,9.7 8.6,8.6 11.9,2 15.4,8.6 23,9.6 17.5,14.7"/><polyline class="left-half" points="12,18.6 5.2,22 6.5,14.8 1,9.7 8.6,8.6 11.9,2"/></svg>
							
							<svg version="1.1" class="bh-star bh-star--3" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24" xml:space="preserve"><path class="outline" d="M12,4.2L14.5,9l0.2,0.5l0.5,0.1l5.5,0.8L16.8,14l-0.4,0.4l0.1,0.5l1,5.3l-5-2.5L12,17.5l-0.4,0.2l-5,2.5L7.5,15l0.1-0.5 L7.2,14l-4-3.7l5.5-0.8l0.5-0.1L9.5,9L12,4.2 M11.9,2L8.6,8.6L1,9.7l5.5,5.1L5.2,22l6.8-3.4l6.8,3.4l-1.3-7.2L23,9.6l-7.6-1L11.9,2 L11.9,2z"/><polygon class="full" points="18.8,22 12,18.6 5.2,22 6.5,14.8 1,9.7 8.6,8.6 11.9,2 15.4,8.6 23,9.6 17.5,14.7"/><polyline class="left-half" points="12,18.6 5.2,22 6.5,14.8 1,9.7 8.6,8.6 11.9,2"/></svg>
							
							<svg version="1.1" class="bh-star bh-star--4" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24" xml:space="preserve"><path class="outline" d="M12,4.2L14.5,9l0.2,0.5l0.5,0.1l5.5,0.8L16.8,14l-0.4,0.4l0.1,0.5l1,5.3l-5-2.5L12,17.5l-0.4,0.2l-5,2.5L7.5,15l0.1-0.5 L7.2,14l-4-3.7l5.5-0.8l0.5-0.1L9.5,9L12,4.2 M11.9,2L8.6,8.6L1,9.7l5.5,5.1L5.2,22l6.8-3.4l6.8,3.4l-1.3-7.2L23,9.6l-7.6-1L11.9,2 L11.9,2z"/><polygon class="full" points="18.8,22 12,18.6 5.2,22 6.5,14.8 1,9.7 8.6,8.6 11.9,2 15.4,8.6 23,9.6 17.5,14.7"/><polyline class="left-half" points="12,18.6 5.2,22 6.5,14.8 1,9.7 8.6,8.6 11.9,2"/></svg>
							
							<svg version="1.1" class="bh-star bh-star--5" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24" xml:space="preserve"><path class="outline" d="M12,4.2L14.5,9l0.2,0.5l0.5,0.1l5.5,0.8L16.8,14l-0.4,0.4l0.1,0.5l1,5.3l-5-2.5L12,17.5l-0.4,0.2l-5,2.5L7.5,15l0.1-0.5 L7.2,14l-4-3.7l5.5-0.8l0.5-0.1L9.5,9L12,4.2 M11.9,2L8.6,8.6L1,9.7l5.5,5.1L5.2,22l6.8-3.4l6.8,3.4l-1.3-7.2L23,9.6l-7.6-1L11.9,2 L11.9,2z"/><polygon class="full" points="18.8,22 12,18.6 5.2,22 6.5,14.8 1,9.7 8.6,8.6 11.9,2 15.4,8.6 23,9.6 17.5,14.7"/><polyline class="left-half" points="12,18.6 5.2,22 6.5,14.8 1,9.7 8.6,8.6 11.9,2"/></svg>
			</div><p>'.$basedon.' '.$count.' '.$review.'</p><a href="#review" class="view_more">'.$view_review.'</a></div>';
		
		endif; ?>
		
		
			<?php
		//}
		//$apiKey= $this->yourFunctionToGetApiKeyFromConfiguration();
		//echo '<br>.hdhhd';
		/* $headers = explode('/', $apiKey);
		$api = $headers[0]; 
		echo $api; */
		?>
    <?php// endif; ?>
    <?php// endif; ?>
</div>
</div>
